// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountController from "./account_controller.js"
application.register("account", AccountController)

import ConfirmationController from "./confirmation_controller.js"
application.register("confirmation", ConfirmationController)

import ContractController from "./contract_controller.js"
application.register("contract", ContractController)

import CounterPartyController from "./counter_party_controller.js"
application.register("counter-party", CounterPartyController)

import CurrencyController from "./currency_controller.js"
application.register("currency", CurrencyController)

import FlatpickrController from "./flatpickr_controller.js"
application.register("flatpickr", FlatpickrController)

import PersistencyController from "./persistency_controller.js"
application.register("persistency", PersistencyController)

import PriceController from "./price_controller.js"
application.register("price", PriceController)

import ReplaceController from "./replace_controller.js"
application.register("replace", ReplaceController)

import RowController from "./row_controller.js"
application.register("row", RowController)

import SelectrController from "./selectr_controller.js"
application.register("selectr", SelectrController)

import TableController from "./table_controller.js"
application.register("table", TableController)

import TransactionController from "./transaction_controller.js"
application.register("transaction", TransactionController)

import UnitController from "./unit_controller.js"
application.register("unit", UnitController)
